# Project: FLP 1 - simplify-bkg   
# Author: Ondrej Sajdik (xsajdi01)
# Year: 2021

all: build

build:
	ghc src/Main.hs src/Simplify.hs src/Types.hs src/ParseInput.hs src/Helper.hs -o simplify-bkg

clean:
	rm simplify-bkg src/*.o src/*.hi
